"""Model registry.

Importing this package registers every table on `Base.metadata`. Alembic's
`env.py` relies on that, so any new model must be re-exported here or it will
be silently missing from autogenerated migrations.
"""

from app.models.admin import Admin, AdminPasswordReset, AdminSession
from app.models.analytics import AnalyticsDailyRollup, AnalyticsEvent, SearchLog
from app.models.audit import AuditLog
from app.models.company import Company
from app.models.job import Job
from app.models.rbac import Permission, Role, role_permissions
from app.models.report import Report
from app.models.taxonomy import Category, Location, Source

__all__ = [
    "Admin",
    "AdminPasswordReset",
    "AdminSession",
    "AnalyticsDailyRollup",
    "AnalyticsEvent",
    "AuditLog",
    "Category",
    "Company",
    "Job",
    "Location",
    "Permission",
    "Report",
    "Role",
    "SearchLog",
    "Source",
    "role_permissions",
]
