"""Alembic environment.

Migrations run through the synchronous psycopg2 driver. Alembic's own work is
sequential, DDL is transactional in PostgreSQL, and a sync driver keeps the
migration path free of event-loop concerns — the async engine is a runtime
concern, not a migration one.

The database URL comes from application settings so there is exactly one place
that knows how to reach the database.
"""

from __future__ import annotations

from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context
from app.core.config import settings

# Importing the model package registers every table on the metadata. Without
# this import, autogenerate would see an empty schema and propose dropping
# everything.
from app.db.base import Base
from app.models import *  # noqa: F401,F403

config = context.config
config.set_main_option("sqlalchemy.url", settings.sync_database_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def include_object(obj, name, type_, reflected, compare_to) -> bool:
    """Keep autogenerate away from objects Alembic does not own.

    Partition children are created by migration and by the monthly worker;
    they must never appear as autogenerated drops.
    """
    if type_ == "table" and (
        name.startswith("analytics_events_") or name.startswith("search_logs_")
    ):
        return False
    return True


def run_migrations_offline() -> None:
    context.configure(
        url=settings.sync_database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
            include_object=include_object,
            # Named constraints make downgrades possible. Without this, Alembic
            # emits unnamed CHECK constraints that cannot be dropped.
            render_as_batch=False,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
