"""Initial schema — 14 tables, enums, extensions and partitions.

Hand-authored rather than autogenerated. Autogenerate cannot express
`PARTITION BY RANGE`, cannot create the partition children, and orders enum
creation unpredictably relative to the tables that use them. A baseline
migration is the one place where writing it by hand is cheaper than correcting
what the tool produced.

Revision ID: 0001_initial_schema
Revises:
Created: 2026-08-14
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# --- enum definitions -----------------------------------------------------
# `create_type=False` on the column definitions below; the types are created
# once here so ordering is explicit.
ENUMS: dict[str, tuple[str, ...]] = {
    "work_type": ("remote", "on_site", "hybrid"),
    "employment_type": ("full_time", "part_time", "contract", "internship"),
    "experience_level": ("intern", "entry", "mid", "senior", "lead", "executive"),
    "job_status": ("draft", "scheduled", "published", "expired", "archived"),
    "salary_period": ("hour", "month", "year"),
    "source_type": ("manual", "scraper", "partner", "community"),
    "report_reason": (
        "broken_link",
        "spam",
        "expired",
        "wrong_information",
        "duplicate",
        "other",
    ),
    "report_status": ("open", "in_review", "resolved", "dismissed"),
    "event_type": (
        "job_viewed",
        "apply_clicked",
        "job_saved",
        "search_submitted",
        "filter_used",
        "job_reported",
    ),
    "device_type": ("mobile", "tablet", "desktop"),
    "session_revoke_reason": (
        "logout",
        "rotated",
        "reuse_detected",
        "password_change",
        "admin_action",
    ),
}

#: Partitions created up front. The monthly worker (Milestone 7) extends this
#: window; a partitioned table with no matching partition rejects the insert,
#: so the window must always run ahead of "now".
INITIAL_PARTITIONS = [
    ("2026_07", "2026-07-01", "2026-08-01"),
    ("2026_08", "2026-08-01", "2026-09-01"),
    ("2026_09", "2026-09-01", "2026-10-01"),
    ("2026_10", "2026-10-01", "2026-11-01"),
]


def _enum(name: str) -> postgresql.ENUM:
    return postgresql.ENUM(*ENUMS[name], name=name, create_type=False)


def upgrade() -> None:
    # --- extensions -------------------------------------------------------
    # citext: case-insensitive uniqueness for emails and slugs.
    # pg_trgm: fuzzy matching for company dedupe and search typo tolerance.
    # unaccent: needed by the Milestone 5 search vector.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")

    for name, values in ENUMS.items():
        rendered = ", ".join(f"'{v}'" for v in values)
        op.execute(f"CREATE TYPE {name} AS ENUM ({rendered})")

    # --- rbac -------------------------------------------------------------
    op.create_table(
        "permissions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("key", postgresql.CITEXT(), nullable=False),
        sa.Column("group_name", sa.String(32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_permissions"),
        sa.UniqueConstraint("key", name="uq_permissions_key"),
    )
    op.create_index("ix_permissions_group_name", "permissions", ["group_name"])

    op.create_table(
        "roles",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("key", postgresql.CITEXT(), nullable=False),
        sa.Column("name", sa.String(64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_roles"),
        sa.UniqueConstraint("key", name="uq_roles_key"),
    )

    op.create_table(
        "role_permissions",
        sa.Column("role_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("permission_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "granted_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name="fk_role_permissions_role_id_roles", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name="fk_role_permissions_permission_id_permissions",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name="pk_role_permissions"),
    )
    op.create_index("ix_role_permissions_permission_id", "role_permissions", ["permission_id"])

    # --- admins -----------------------------------------------------------
    op.create_table(
        "admins",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.String(120), nullable=False),
        sa.Column("role_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "password_changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "failed_attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name="fk_admins_role_id_roles", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["admins.id"], name="fk_admins_created_by_admins", ondelete="SET NULL"
        ),
        sa.CheckConstraint("failed_attempts >= 0", name="failed_attempts_non_negative"),
        sa.PrimaryKeyConstraint("id", name="pk_admins"),
        sa.UniqueConstraint("email", name="uq_admins_email"),
    )
    op.create_index("ix_admins_role_id", "admins", ["role_id"])
    op.create_index(
        "ix_admins_is_active", "admins", ["is_active"], postgresql_where=sa.text("is_active")
    )

    op.create_table(
        "admin_sessions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("admin_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.String(64), nullable=False),
        sa.Column("family_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("replaced_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", _enum("session_revoke_reason"), nullable=True),
        sa.Column("user_agent", sa.String(400), nullable=True),
        sa.Column("ip_hash", sa.String(64), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["admins.id"],
            name="fk_admin_sessions_admin_id_admins",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by"],
            ["admin_sessions.id"],
            name="fk_admin_sessions_replaced_by_admin_sessions",
            ondelete="SET NULL",
        ),
        sa.CheckConstraint("expires_at > issued_at", name="expiry_after_issue"),
        sa.PrimaryKeyConstraint("id", name="pk_admin_sessions"),
        sa.UniqueConstraint("token_hash", name="uq_admin_sessions_token_hash"),
    )
    op.create_index(
        "ix_admin_sessions_admin_id_revoked_at", "admin_sessions", ["admin_id", "revoked_at"]
    )
    op.create_index("ix_admin_sessions_family_id", "admin_sessions", ["family_id"])
    op.create_index("ix_admin_sessions_expires_at", "admin_sessions", ["expires_at"])

    # --- taxonomy ---------------------------------------------------------
    op.create_table(
        "categories",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(80), nullable=False),
        sa.Column("slug", postgresql.CITEXT(), nullable=False),
        sa.Column("icon", sa.String(16), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("job_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("job_count >= 0", name="job_count_non_negative"),
        sa.PrimaryKeyConstraint("id", name="pk_categories"),
        sa.UniqueConstraint("slug", name="uq_categories_slug"),
    )
    op.create_index("ix_categories_is_active_sort_order", "categories", ["is_active", "sort_order"])

    op.create_table(
        "locations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("city", sa.String(80), nullable=True),
        sa.Column("region", sa.String(80), nullable=True),
        sa.Column("country", sa.String(2), server_default=sa.text("'PK'"), nullable=False),
        sa.Column("slug", postgresql.CITEXT(), nullable=False),
        sa.Column("display_name", sa.String(160), nullable=False),
        sa.Column("is_remote", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("job_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("is_remote OR city IS NOT NULL", name="city_required_unless_remote"),
        sa.CheckConstraint("job_count >= 0", name="job_count_non_negative"),
        sa.PrimaryKeyConstraint("id", name="pk_locations"),
        sa.UniqueConstraint("slug", name="uq_locations_slug"),
    )
    op.create_index("ix_locations_country_city", "locations", ["country", "city"])
    op.create_index(
        "ix_locations_is_remote", "locations", ["is_remote"], postgresql_where=sa.text("is_remote")
    )

    op.create_table(
        "sources",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("slug", postgresql.CITEXT(), nullable=False),
        sa.Column("type", _enum("source_type"), nullable=False),
        sa.Column("base_url", sa.String(500), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "config", postgresql.JSONB(), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="pk_sources"),
        sa.UniqueConstraint("slug", name="uq_sources_slug"),
    )
    op.create_index("ix_sources_is_active_type", "sources", ["is_active", "type"])

    op.create_table(
        "companies",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(160), nullable=False),
        sa.Column("slug", postgresql.CITEXT(), nullable=False),
        sa.Column("logo_url", sa.String(500), nullable=True),
        sa.Column("monogram", sa.String(2), nullable=True),
        sa.Column("palette_index", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("website", sa.String(500), nullable=True),
        sa.Column("verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("job_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("palette_index BETWEEN 0 AND 5", name="palette_index_in_range"),
        sa.CheckConstraint("job_count >= 0", name="job_count_non_negative"),
        sa.PrimaryKeyConstraint("id", name="pk_companies"),
        sa.UniqueConstraint("slug", name="uq_companies_slug"),
    )
    op.execute("CREATE INDEX ix_companies_name_trgm ON companies USING gin (name gin_trgm_ops)")

    # --- jobs -------------------------------------------------------------
    op.create_table(
        "jobs",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("slug", postgresql.CITEXT(), nullable=False),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("company_name", sa.String(160), nullable=False),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("company_logo", sa.String(500), nullable=True),
        sa.Column("logo_palette", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("category_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("location_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("work_type", _enum("work_type"), nullable=False),
        sa.Column("employment_type", _enum("employment_type"), nullable=False),
        sa.Column("experience_level", _enum("experience_level"), nullable=False),
        sa.Column("experience_min_years", sa.SmallInteger(), nullable=True),
        sa.Column("experience_max_years", sa.SmallInteger(), nullable=True),
        sa.Column("salary_min", sa.Numeric(12, 2), nullable=True),
        sa.Column("salary_max", sa.Numeric(12, 2), nullable=True),
        sa.Column("salary_currency", sa.String(3), server_default=sa.text("'PKR'"), nullable=False),
        sa.Column(
            "salary_period",
            _enum("salary_period"),
            server_default=sa.text("'month'"),
            nullable=False,
        ),
        sa.Column(
            "salary_is_disclosed", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "requirements",
            postgresql.JSONB(),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "responsibilities",
            postgresql.JSONB(),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "benefits", postgresql.JSONB(), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("apply_url", sa.String(1000), nullable=False),
        sa.Column("status", _enum("job_status"), server_default=sa.text("'draft'"), nullable=False),
        sa.Column("featured", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("featured_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("view_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("apply_click_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("save_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("location_text", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("skills_text", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("updated_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name="fk_jobs_company_id_companies",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name="fk_jobs_category_id_categories",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name="fk_jobs_location_id_locations",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name="fk_jobs_source_id_sources", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"], ["admins.id"], name="fk_jobs_verified_by_admins", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["admins.id"], name="fk_jobs_created_by_admins", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["admins.id"], name="fk_jobs_updated_by_admins", ondelete="SET NULL"
        ),
        sa.CheckConstraint(
            "status <> 'published' OR published_at IS NOT NULL", name="published_requires_timestamp"
        ),
        sa.CheckConstraint(
            "NOT featured OR status = 'published'", name="featured_requires_published"
        ),
        sa.CheckConstraint(
            "NOT verified OR verified_by IS NOT NULL", name="verified_requires_verifier"
        ),
        sa.CheckConstraint(
            "salary_max IS NULL OR salary_min IS NULL OR salary_max >= salary_min",
            name="salary_range_ordered",
        ),
        sa.CheckConstraint(
            "experience_max_years IS NULL OR experience_min_years IS NULL OR experience_max_years >= experience_min_years",
            name="experience_range_ordered",
        ),
        sa.CheckConstraint(
            "experience_min_years IS NULL OR experience_min_years BETWEEN 0 AND 50",
            name="experience_min_in_range",
        ),
        sa.CheckConstraint("length(title) BETWEEN 3 AND 200", name="title_length"),
        sa.CheckConstraint("length(description) >= 50", name="description_min_length"),
        sa.CheckConstraint("apply_url ~ '^https?://'", name="apply_url_is_http"),
        sa.CheckConstraint("logo_palette BETWEEN 0 AND 5", name="logo_palette_in_range"),
        sa.CheckConstraint(
            "view_count >= 0 AND apply_click_count >= 0 AND save_count >= 0",
            name="counters_non_negative",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_jobs"),
    )
    op.create_index(
        "uq_jobs_slug_active",
        "jobs",
        ["slug"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.execute(
        "CREATE INDEX ix_jobs_status_published_at ON jobs (status, published_at DESC) WHERE deleted_at IS NULL"
    )
    op.execute(
        "CREATE INDEX ix_jobs_category_id_status ON jobs (category_id, status, published_at DESC)"
    )
    op.execute(
        "CREATE INDEX ix_jobs_location_id_status ON jobs (location_id, status, published_at DESC)"
    )
    op.create_index("ix_jobs_work_type_status", "jobs", ["work_type", "status"])
    op.create_index("ix_jobs_employment_type_status", "jobs", ["employment_type", "status"])
    op.create_index("ix_jobs_experience_level_status", "jobs", ["experience_level", "status"])
    op.execute(
        "CREATE INDEX ix_jobs_featured_published_at ON jobs (featured, published_at DESC) WHERE featured"
    )
    op.execute("CREATE INDEX ix_jobs_expiry_date ON jobs (expiry_date) WHERE status = 'published'")
    op.execute("CREATE INDEX ix_jobs_source_id_published_at ON jobs (source_id, published_at DESC)")
    op.execute("CREATE INDEX ix_jobs_company_id ON jobs (company_id) WHERE company_id IS NOT NULL")
    op.execute("CREATE INDEX ix_jobs_created_by_created_at ON jobs (created_by, created_at DESC)")
    op.execute("CREATE INDEX ix_jobs_title_trgm ON jobs USING gin (title gin_trgm_ops)")

    # --- reports ----------------------------------------------------------
    op.create_table(
        "reports",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("reason", _enum("report_reason"), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("reporter_email", postgresql.CITEXT(), nullable=True),
        sa.Column("reporter_ip_hash", sa.String(64), nullable=False),
        sa.Column("session_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "status", _enum("report_status"), server_default=sa.text("'open'"), nullable=False
        ),
        sa.Column("resolution_note", sa.String(500), nullable=True),
        sa.Column("resolved_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name="fk_reports_job_id_jobs", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["admins.id"],
            name="fk_reports_resolved_by_admins",
            ondelete="SET NULL",
        ),
        sa.CheckConstraint("comment IS NULL OR length(comment) <= 1000", name="comment_length"),
        sa.CheckConstraint(
            "status NOT IN ('resolved', 'dismissed') OR (resolved_by IS NOT NULL AND resolution_note IS NOT NULL)",
            name="terminal_requires_resolution",
        ),
        sa.CheckConstraint(
            "reason <> 'other' OR comment IS NOT NULL", name="other_requires_comment"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_reports"),
    )
    op.execute("CREATE INDEX ix_reports_status_created_at ON reports (status, created_at DESC)")
    op.create_index("ix_reports_job_id_status", "reports", ["job_id", "status"])
    op.execute(
        "CREATE INDEX ix_reports_reporter_ip_hash_created_at ON reports (reporter_ip_hash, created_at DESC)"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_reports_job_session_open ON reports (job_id, session_id) "
        "WHERE status = 'open' AND session_id IS NOT NULL"
    )

    # --- analytics (partitioned) -----------------------------------------
    op.execute(
        """
        CREATE TABLE analytics_events (
            id            bigint GENERATED BY DEFAULT AS IDENTITY,
            occurred_at   timestamptz NOT NULL DEFAULT now(),
            event_type    event_type NOT NULL,
            session_id    uuid NOT NULL,
            job_id        uuid REFERENCES jobs(id) ON DELETE SET NULL,
            source_id     uuid,
            category_id   uuid,
            filters       jsonb,
            referrer_host varchar(255),
            device_type   device_type,
            country       varchar(2),
            CONSTRAINT pk_analytics_events PRIMARY KEY (occurred_at, id)
        ) PARTITION BY RANGE (occurred_at)
        """
    )
    op.execute(
        "CREATE INDEX ix_analytics_events_job_type_time ON analytics_events (job_id, event_type, occurred_at DESC)"
    )
    op.execute(
        "CREATE INDEX ix_analytics_events_type_time ON analytics_events (event_type, occurred_at DESC)"
    )
    op.execute(
        "CREATE INDEX ix_analytics_events_session_time ON analytics_events (session_id, occurred_at)"
    )

    op.execute(
        """
        CREATE TABLE search_logs (
            id               bigint GENERATED BY DEFAULT AS IDENTITY,
            occurred_at      timestamptz NOT NULL DEFAULT now(),
            session_id       uuid NOT NULL,
            raw_query        varchar(200) NOT NULL,
            normalised_query varchar(200) NOT NULL,
            filters          jsonb NOT NULL DEFAULT '{}'::jsonb,
            result_count     integer NOT NULL,
            was_degraded     boolean NOT NULL DEFAULT false,
            clicked_job_id   uuid REFERENCES jobs(id) ON DELETE SET NULL,
            click_position   smallint,
            response_ms      integer,
            CONSTRAINT pk_search_logs PRIMARY KEY (occurred_at, id),
            CONSTRAINT ck_search_logs_result_count_non_negative CHECK (result_count >= 0),
            CONSTRAINT ck_search_logs_click_position_positive
                CHECK (click_position IS NULL OR click_position > 0)
        ) PARTITION BY RANGE (occurred_at)
        """
    )
    op.execute(
        "CREATE INDEX ix_search_logs_normalised_query_time ON search_logs (normalised_query, occurred_at DESC)"
    )
    op.execute(
        "CREATE INDEX ix_search_logs_zero_results ON search_logs (occurred_at DESC) WHERE result_count = 0"
    )

    for suffix, start, end in INITIAL_PARTITIONS:
        for parent in ("analytics_events", "search_logs"):
            op.execute(
                f"CREATE TABLE {parent}_{suffix} PARTITION OF {parent} "
                f"FOR VALUES FROM ('{start}') TO ('{end}')"
            )

    # --- audit ------------------------------------------------------------
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("admin_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("action", sa.String(64), nullable=False),
        sa.Column("entity_type", sa.String(32), nullable=False),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("before", postgresql.JSONB(), nullable=True),
        sa.Column("after", postgresql.JSONB(), nullable=True),
        sa.Column("ip_hash", sa.String(64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"], ["admins.id"], name="fk_audit_logs_admin_id_admins", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_audit_logs"),
    )
    op.execute(
        "CREATE INDEX ix_audit_logs_entity_created_at ON audit_logs (entity_type, entity_id, created_at DESC)"
    )
    op.execute(
        "CREATE INDEX ix_audit_logs_admin_id_created_at ON audit_logs (admin_id, created_at DESC)"
    )
    op.execute(
        "CREATE INDEX ix_audit_logs_action_created_at ON audit_logs (action, created_at DESC)"
    )


def downgrade() -> None:
    # Reverse dependency order. Partition children drop with their parent.
    op.drop_table("audit_logs")
    op.execute("DROP TABLE IF EXISTS search_logs CASCADE")
    op.execute("DROP TABLE IF EXISTS analytics_events CASCADE")
    op.drop_table("reports")
    op.drop_table("jobs")
    op.drop_table("companies")
    op.drop_table("sources")
    op.drop_table("locations")
    op.drop_table("categories")
    op.drop_table("admin_sessions")
    op.drop_table("admins")
    op.drop_table("role_permissions")
    op.drop_table("roles")
    op.drop_table("permissions")

    for name in reversed(list(ENUMS)):
        op.execute(f"DROP TYPE IF EXISTS {name}")

    # Extensions are deliberately left in place: they may be shared with other
    # schemas in the same database, and dropping them is not our call.
